### ISSUE TITLE
The issues for the full objective configuration

### ISSUE THREAD

**Issue by SherLockLi99** [cnzzx/GeMap#18]
Hello！When I run the following command：`python tools/gemap/custom_nusc_map_converter.py --root-path ./data/hdmap/nuscenes --out-dir ./data/hdmap/nuscenes/full --extra-tag nuscenes --version v1.0 --canbus ./data/hdmap`
I get the following error, what is the cause of this?
`[                                                  ] 0/34149, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/gemap/custom_nusc_map_converter.py", line 928, in <module>
    nuscenes_data_prep(
  File "tools/gemap/custom_nusc_map_converter.py", line 869, in nuscenes_data_prep
    create_nuscenes_infos(
  File "tools/gemap/custom_nusc_map_converter.py", line 825, in create_nuscenes_infos
    train_nusc_infos, val_nusc_infos = _fill_trainval_infos(
  File "tools/gemap/custom_nusc_map_converter.py", line 340, in _fill_trainval_infos
    info = obtain_vectormap(nusc_maps, map_explorer, info, point_cloud_range)
  File "tools/gemap/custom_nusc_map_converter.py", line 371, in obtain_vectormap
    map_anns = vector_map.gen_vectorized_samples(lidar2global_translation, lidar2global_rotation)
  File "tools/gemap/custom_nusc_map_converter.py", line 442, in gen_vectorized_samples
    centerline_list = self.centerline_geoms_to_instances(centerline_geom)
  File "tools/gemap/custom_nusc_map_converter.py", line 672, in centerline_geoms_to_instances
    centerline_geoms_list,pts_G = self.union_centerline(geoms_dict)
  File "tools/gemap/custom_nusc_map_converter.py", line 743, in union_centerline
    paths = nx.all_simple_paths(pts_G, root, leaves)
  File "/home/hwt/anaconda3/envs/npn/lib/python3.8/site-packages/networkx/algorithms/simple_paths.py", line 202, in all_simple_paths
    raise nx.NodeNotFound('target node %s not in graph' % target)
networkx.exception.NodeNotFound: target node [(15.0, 2.355), (15.0, -2.636), (4.167, -30.0), (-15.0, 15.813), (0.284, -30.0)] not in graph
`

**Comment by cnzzx** [comment]
A similar issue is [here](https://github.com/cnzzx/GeMap/issues/3) and you can try to update your networkx version to 3.1.
